# Generated by Django 3.2.6 on 2021-12-11 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=6)),
                ('course_credit', models.IntegerField()),
                ('course_title', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('bin', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('nsu_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_access',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainapp.customer')),
                ('student_name', models.BooleanField(default=False)),
                ('student_id', models.BooleanField(default=False)),
                ('program_name', models.BooleanField(default=False)),
                ('student_email', models.BooleanField(default=False)),
                ('student_cell', models.BooleanField(default=False)),
                ('student_nid', models.BooleanField(default=False)),
                ('student_dob', models.BooleanField(default=False)),
                ('student_sex', models.BooleanField(default=False)),
                ('student_bloodGroup', models.BooleanField(default=False)),
                ('student_citizenship', models.BooleanField(default=False)),
                ('student_maritalStatus', models.BooleanField(default=False)),
                ('student_currentAddress', models.BooleanField(default=False)),
                ('student_fatherName', models.BooleanField(default=False)),
                ('student_motherName', models.BooleanField(default=False)),
                ('student_parentAddress', models.BooleanField(default=False)),
                ('student_parentPhone', models.BooleanField(default=False)),
                ('Academic_Information', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField()),
                ('year', models.CharField(max_length=4)),
                ('semester', models.CharField(max_length=6)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('program_name', models.CharField(max_length=100)),
                ('personal_email', models.EmailField(max_length=50)),
                ('cell_phone', models.CharField(max_length=15)),
                ('nid', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7)),
                ('blood_group', models.CharField(max_length=5)),
                ('citizenship', models.CharField(max_length=20)),
                ('marital_status', models.CharField(max_length=10)),
                ('current_address', models.TextField(blank=True)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('parent_address', models.TextField(blank=True)),
                ('parent_phone', models.CharField(max_length=15)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20)),
                ('est_available_yearly', models.FloatField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.student')),
            ],
        ),
    ]
